version: '3.8'

services:

  users-system:
    image: sogolonmvj/users-system
    container_name: users-system
    ports:
      - "8080:8084"
    restart: always
    links:
      - users-system-postgres
    depends_on:
      - users-system-postgres
    networks:
      - host
  users-system-postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./database-data:/data/db
    environment:
      - POSTGRES_DB=customer_registration
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0wN3r
    networks:
      - host
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    links:
      - users-system
    depends_on:
      - users-system
    networks:
      - host

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus:/etc/prometheus
    networks:
      - host
    links:
      - users-system
    depends_on:
      - users-system

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_PROTOCOL: http
      GF_SERVER_HTTP: 3000
    networks:
      - host
    links:
      - prometheus
    depends_on:
      - prometheus

networks:
  host: