server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

info:
  app:
    version: '@project.version@'
    name: '@project.name@'
    java:
      version: '@java.version@'
    description: '@project.description@'

management:
  endpoints:
    web:
      exposure:
        include: '*'

#spring:
#  application:
#    name: 'users-system'